import { z } from 'zod'

// Generated property data schema
export const GeneratedPropertySchema = z.object({
  zpid: z.string(),
  address: z.string(),
  zipCode: z.string(),
  latitude: z.number(),
  longitude: z.number(),
  bedrooms: z.number().int(),
  bathrooms: z.number(),
  sqft: z.number().int(),
  lotSizeSqft: z.number().int().optional(),
  yearBuilt: z.number().int(),
  propertyType: z.string(),
  stories: z.number().int().optional(),
  garageSpaces: z.number().int().optional(),
  parkingSpaces: z.number().int().optional(),
  price: z.number().int(),
  pricePerSqft: z.number().optional(),
  hoaFee: z.number().int().optional(),
  propertyTax: z.number().int().optional(),
  status: z.string().default('For Sale'),
  listingType: z.string().optional(),
  listing: z.object({
    listDate: z.string(),
    daysOnMarket: z.number().int().optional(),
    description: z.string().optional(),
    keyFeatures: z.array(z.string()).optional(),
    agentName: z.string().optional(),
    agentPhone: z.string().optional(),
    agentEmail: z.string().optional(),
    brokerage: z.string().optional(),
    openHouseDates: z.array(z.string()).optional(),
    tourAvailable: z.boolean().optional(),
    virtualTourUrl: z.string().optional(),
    originalPrice: z.number().int().optional(),
    priceChanges: z.array(z.any()).optional(),
  }).optional(),
  features: z.object({
    flooringTypes: z.array(z.string()).optional(),
    kitchenFeatures: z.array(z.string()).optional(),
    bathroomFeatures: z.array(z.string()).optional(),
    fireplace: z.boolean().optional(),
    fireplaceCount: z.number().int().optional(),
    laundryFeatures: z.string().optional(),
    cooling: z.string().optional(),
    heating: z.string().optional(),
    yardFeatures: z.array(z.string()).optional(),
    pool: z.boolean().optional(),
    spa: z.boolean().optional(),
    garageType: z.string().optional(),
    securityFeatures: z.array(z.string()).optional(),
    accessibilityFeatures: z.array(z.string()).optional(),
    greenFeatures: z.array(z.string()).optional(),
    schoolDistrict: z.string().optional(),
    walkabilityScore: z.number().int().optional(),
    transitScore: z.number().int().optional(),
    bikeScore: z.number().int().optional(),
  }).optional(),
  photos: z.array(z.object({
    imageUrl: z.string().optional(),
    caption: z.string().optional(),
    roomType: z.string().optional(),
    isPrimary: z.boolean().optional(),
    sortOrder: z.number().int().optional(),
  })).optional(),
})

export type GeneratedProperty = z.infer<typeof GeneratedPropertySchema> 